### ISSUE TITLE
Include some sample files

### ISSUE THREAD

**Issue by andybak** [Nodi3d/nodi#14]
I suspect most people are similar to me - I loathe reading docs until I've had a play around.

Unless I've overlooked something, there's no sample files or examples I can load in nodi? I find these the most interesting way to evaluate a new tool and it goes a long way towards making me stick around until I've over the initial learning curve.

**Comment by mattatz** [comment]
@andybak 
I have added the link to https://nodi3d.github.io/docs/user/examples/ in header by #15 👍
