### ISSUE TITLE
Allow writing out arbitrary text

### ISSUE THREAD

**Issue by WillAdams** [Nodi3d/nodi#426]
If it was possible to write out arbitrary text as part of modeling it would be possible to export G-code, allowing one to directly do CAM.

**Comment by mattatz** [comment]
@WillAdams 

Apologies for the delayed response.
Nodi is currently developing Version 2, and Version 1 has now been deprecated. Version 2 is available as an early access release at https://v2.nodi3d.com/.

I appreciate your feedback and will consider it for inclusion in Version 2. If possible, I’d be grateful if you could also share your feedback on the Version 2 forum.
