### ISSUE TITLE
[FEATURE REQUEST] Angled and rounded inside corners

### ISSUE THREAD

**Issue by cndjonno** [Nodi3d/nodi#427]
It would be great if the tool had an option to angle all the inside edges and corners either 45 degrees or rounded for 3d printing.

The angled even a tiny bit would keep debris from being stuck in corners and easy to print.

The rounded would make these great to remove items from like board game items, washers.

**Comment by mattatz** [comment]
@cndjonno 

Apologies for the delayed response.
Nodi is currently developing Version 2, and Version 1 has now been deprecated. Version 2 is available as an early access release at https://v2.nodi3d.com/.

I appreciate your feedback and will consider it for inclusion in Version 2. If possible, I’d be grateful if you could also share your feedback on the Version 2 forum.
